name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "Bierpongregelwerk.tex"

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: 'Bierpongregelwerk.pdf'
          if-no-files-found: error
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["build-release"]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Get release artifact
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Bierpongregelwerk.pdf
